spring:
  profiles.active: dev

server:
  servlet:
    context-path: /api/v1

weatherService:
  config:
    weatherDataApi:
      version: 2.5
      unit: metric
      current:
        weatherDataApiBaseUrl: http://api.openweathermap.org/data
        weatherDataApiEndpoint: /current
        httpMethod: GET
      history:
        count: 5

---
spring:
  profiles: dev
server:
  port: 9090

weatherService:
  config:
    weatherDataApi:
      history:
        count: 5

---
spring:
  profiles: qa

server:
  port: 9091

weatherService:
  config:
    weatherDataApi:
      history:
        count: 10

---
spring:
  profiles: stage

server:
  port: 9092

weatherService:
  config:
    weatherDataApi:
      history:
        count: 15

---
spring:
  profiles: prod

server:
  port: 80

weatherService:
  config:
    weatherDataApi:
      history:
        count: 20